### ISSUE TITLE
serialize as [[key, value], ...] ?

### ISSUE THREAD

**Issue by hildjj** [shanewholloway/js-cbor-codec#4]
Regarding CBOR-259-spec--explicit-maps.md

In my opinion, it should be possible to encode a Map as an array of entries rather than an object, so that the decoder won't lose information in the decoding process before handing off to the function to process the tag.

so for example:

```js
new Map([[1, 2], [3, 4]])
```

would get encoded as:

```
  d9                --  next 2 bytes
    0103            -- Tag #259
      82            -- Array, 2 items
        82          -- [0], Array, 2 items
          01        -- [0], 1
          02        -- [1], 2
        82          -- [1], Array, 2 items
          03        -- [0], 3
          04        -- [1], 4
0xd9010382820102820304
```

Maybe that needs to be a whole new tag number at this point?

**Comment by shanewholloway** [comment]
@hildjj -- first, thanks for reaching out! Props for creating [`cbor-web`](https://github.com/hildjj/node-cbor/releases/tag/v7.0.0)

My primary reason for selecting the CBOR map tag (`0xA?`) was one of semantics -- "maps" being a collection of pairs. This allowed the 2-element arrays to be implicit and saving an extra byte (`0x82`) times the number of entries in the map.

As the actual bytes-on-the-wire encoding is ordered, it is up to the data structure selection & implementation of the decoder as to whether information is lost in handoff. For example, the decoder could select to use a more explicit [OrderedMap](https://github.com/marijnh/orderedmap) or Python's [OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict).  Digging into documentation, I discovered that JavaScript's Map is order preserving [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).
> The Map object holds key-value pairs and remembers the original insertion order of the keys.

That claim is backed by [EMCA 262 `.forEach()` spec](https://262.ecma-international.org#sec-map.prototype.foreach) calling out _"in key insertion order"_ explicitly, as well as the pseudocode of [`MapIteratorPrototype.next()`](https://262.ecma-international.org#sec-%mapiteratorprototype%.next) strongly indicating key insertion order traversal for all the iterable methods.

That said, the default `cbor-codec` would retain only the most recent `(key, value)` pairs for duplicate keys, and would thus discard some information.

**Comment by shanewholloway** [comment]
re: _Maybe that needs to be a whole new tag number at this point?_

A new tag would probably be the right thing to do. One of the things I appreciate about the core CBOR spec is the "one right way" to encode the core values. Granted the extensions make "the one right encoding" stance fuzzier.

**Comment by hildjj** [comment]
I started writing something up last night, decided to put in a section about why I chose this instead of other approaches, and realized that [[key, value], ...] was probably not right either unless you were a JavaScript programmer.  We already have an encoding for maps that we should probably reuse; so tagX([key, value, key, value, ...]) probably makes more sense.

I'll update that doc and link to it here; we can decide from there what to do with it, where "ignore it" will be one of the choices. :)

**Comment by hildjj** [comment]
Please send comments or PRs on https://github.com/hildjj/cbor-map-entries

**Comment by hildjj** [comment]
@cabo do you have any opinions?

**Comment by cabo** [comment]
Yes!  See also <https://mailarchive.ietf.org/arch/msg/cbor/Pfa60hJmnAYCSXTK3A_dqNyldDM>
I'd do item-by-item comments, but I'm still confused why github doesn't allow that on markdown files...

**Comment by hildjj** [comment]
It's really gross, but you can fake it with a "PR" that includes all of the code: https://astrofrog.github.io/blog/2013/04/10/how-to-conduct-a-full-code-review-on-github/ or https://gist.github.com/lopezjurip/56fbe6d00f35824988dd7684e0d6dc48

I'm not sure how that would look for a complicated project, but i bet it would be a mess.

**Comment by hildjj** [comment]
Also see https://github.com/Sekenre/cbor-ordered-map-spec/blob/master/CBOR_Ordered_Map.md from CBOR mailing list traffic.

**Comment by shanewholloway** [comment]
And also in the Map space, https://github.com/ecorm/cbor-tag-text-key-map

**Comment by shanewholloway** [comment]
Implemented a round-trip encoder/decoder for [Ordered Maps for CBOR](https://github.com/Sekenre/cbor-ordered-map-spec/blob/master/CBOR_Ordered_Map.md) spec as an [example/demo_tag_tbd279.mjs](https://github.com/shanewholloway/js-cbor-codec/blob/master/examples/demo_tag_tbd279.mjs).

This thread gave me the opportunity to dig back in to CBOR-codec and finish up the custom tag encoders/decoders interface.

On that note, is there something specific `cbor-codec` can do to improve interoperability? Or is this issue resolved / overcome by events?

**Comment by hildjj** [comment]
Looks like it should interop fine.  See my code sketch here: https://github.com/Sekenre/cbor-ordered-map-spec/blob/master/examples/js/example.js
